# Generated by Django 2.0.4 on 2018-12-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='passWord',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='userName',
            field=models.CharField(default='', max_length=100, verbose_name='登陆名'),
        ),
    ]
