# Generated by Django 2.0.4 on 2018-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='OsType',
            field=models.CharField(choices=[(0, 'linux'), (1, 'windows'), (2, 'mac')], default=0, max_length=100, verbose_name='服务器类型'),
        ),
    ]
