# Generated by Django 2.0.4 on 2018-12-04 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0002_auto_20181204_1440'),
        ('project', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Crawler')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name': '爬虫-项目-关系',
                'verbose_name_plural': '爬虫-项目-关系',
            },
        ),
        migrations.CreateModel(
            name='CrawlerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Crawler')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
            options={
                'verbose_name': '爬虫-服务器-关系',
                'verbose_name_plural': '爬虫-服务器-关系',
            },
        ),
        migrations.AlterUniqueTogether(
            name='crawlerserver',
            unique_together={('crawler', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='crawlerproject',
            unique_together={('crawler', 'project')},
        ),
    ]
