# Generated by Django 2.1.3 on 2018-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_cstatus_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(default=None, max_length=255)),
                ('cpu', models.CharField(default=None, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codes.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='cstatus',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
