# Generated by Django 2.0.4 on 2018-12-04 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlerName', models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='工程名（英文）')),
                ('webName', models.CharField(default='', max_length=100, verbose_name='网站名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('type', models.IntegerField(choices=[(0, '定向爬虫'), (1, '漫游爬虫'), (2, '自定义爬虫')], default=0, verbose_name='爬虫类型')),
                ('egg', models.CharField(blank=True, max_length=255, null=True, verbose_name='egg文件')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='projects/')),
                ('conf', models.TextField(blank=True, default='', null=True, verbose_name='配置')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('built_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('generated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '爬虫',
                'verbose_name_plural': '爬虫',
            },
        ),
        migrations.CreateModel(
            name='CrawlerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Crawler')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name': '爬虫-项目-关系',
                'verbose_name_plural': '爬虫-项目-关系',
            },
        ),
        migrations.CreateModel(
            name='CrawlerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Crawler')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
            options={
                'verbose_name': '爬虫-服务器-关系',
                'verbose_name_plural': '爬虫-服务器-关系',
            },
        ),
        migrations.AddField(
            model_name='crawler',
            name='project',
            field=models.ManyToManyField(through='crawler.CrawlerProject', to='project.Project'),
        ),
        migrations.AddField(
            model_name='crawler',
            name='server',
            field=models.ManyToManyField(through='crawler.CrawlerServer', to='server.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='crawlerserver',
            unique_together={('crawler', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='crawlerproject',
            unique_together={('crawler', 'project')},
        ),
    ]
