# Generated by Django 2.0.4 on 2018-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crawlerproject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crawlerproject',
            name='crawler',
        ),
        migrations.RemoveField(
            model_name='crawlerproject',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='crawlerserver',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crawlerserver',
            name='crawler',
        ),
        migrations.RemoveField(
            model_name='crawlerserver',
            name='server',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='project',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='server',
        ),
        migrations.DeleteModel(
            name='CrawlerProject',
        ),
        migrations.DeleteModel(
            name='CrawlerServer',
        ),
    ]
